## Set the API endpoint used to create the Deployment resource.
apiVersion: apps/v1
## Define the type of the resource.
kind: Namespace
metadata:
  creationTimestamp: null
  name: {{ .Values.namespace.name }}
spec: {}
status: {}
