namespace: sandbox
image: techtrends:latest
name: techtrends
replicas: 1
resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits: 
    memory: 128Mi
    CPU: 500m
container port: 3111
liveness probe:
  path: /healthz
  port: 3111
readiness probe:
  path: /healthz
  port: 3111
