apiVersion: v1
kind: Service
namespace: sandbox
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
spec:
  ports:
  - name: techtrends
    port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends
  type: ClusterIP
status:
  loadBalancer: {}
