AppName: techtrends
namespace:
  name: sandbox
  apps: techtrends

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: catzzzlol/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits: 
    memory: 128Mi
    CPU: 500m
    
ports:
    containerPort: 3111
    protocol: TCP
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111
livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
